// Canonical event contract — imported by server AND (conceptually mirrored by) adapters.
// Frozen by Unit 0. Downstream units import from here; do not redefine these shapes.
import { z } from "zod";

export type EventSource = "claude-code" | "opencode" | "codex";

export type EventType =
  | "session_start"
  | "session_end"
  | "tool_call" // a single tool invocation (Bash, Edit, Write, Read, ...)
  | "turn_complete" // agent finished a full turn (Codex's only reliable granularity)
  | "file_edit" // a file was created/modified/deleted
  | "checkpoint"; // manual "hey narrator, log this" — post-MVP; no producer wired yet

export type Outcome = "success" | "failure" | "unknown";

export interface KibitzerEventDetail {
  tool?: string; // e.g. "Bash", "Edit", "Write"
  command?: string; // for Bash-type calls, the literal command (redact secrets)
  filePath?: string;
  outcome?: Outcome;
  isDestructive?: boolean; // set by the SERVER's classifier (pipeline step 0), never the model
  message?: string; // last_assistant_message on turn/session end; user text on checkpoint
  raw?: unknown; // original native payload, kept for debugging, never shown in UI
}

export interface KibitzerEvent {
  id: string; // uuid v4, generated by the adapter (crypto.randomUUID())
  sessionId: string; // stable per build session
  source: EventSource;
  type: EventType;
  timestamp: string; // ISO 8601 (new Date().toISOString())
  detail: KibitzerEventDetail;
}

// ---- Realtime / API response shapes (shared so app + dashboard + routes agree) ----

/** One entry in the feed. Broadcast on `replay` and `narration` SSE frames. */
export interface FeedItem {
  event: KibitzerEvent;
  dramaScore: number; // 0–100
  narration: string | null; // null until LLM resolves
  audioUrl: string | null; // "/api/tts?eventId=…" once TTS ready
}

/** GET /session/:id/analytics response. */
export interface Analytics {
  sessionId: string;
  durationMs: number;
  toolCallsByType: Record<string, number>;
  filesTouched: { path: string; editCount: number }[];
  tests: { pass: number; fail: number };
  backtrackCount: number;
  riskLog: {
    eventId: string;
    timestamp: string;
    logLine: string;
    dramaScore: number;
  }[];
}

/** POST /session/:id/end and GET /session/:id/devpost response. */
export interface Devpost {
  post: string;
  tweetThread: string[];
}

export type PersonaKey = "sports" | "nature";

// ---- SSE frame payloads (the `data` of each named frame; see api-reference.md) ----
// `audioUrl` is BASE-RELATIVE (e.g. "/api/tts?eventId=…"); the app prefixes its paired <base>.

export interface HelloFrame {
  sessionId: string | null;
}
export interface ScoreFrame {
  eventId: string;
  dramaScore: number;
}
export interface AudioFrame {
  eventId: string;
  audioUrl: string;
}
export interface PersonaFrame {
  persona: PersonaKey;
}
// `replay` and `narration` frames carry a `FeedItem`.

export type SseFrameKind =
  | "hello"
  | "replay"
  | "score"
  | "narration"
  | "audio"
  | "persona"
  | "ping";

// ---- Validation ----

export const eventDetailSchema = z.object({
  tool: z.string().optional(),
  command: z.string().optional(),
  filePath: z.string().optional(),
  outcome: z.enum(["success", "failure", "unknown"]).optional(),
  isDestructive: z.boolean().optional(),
  message: z.string().optional(),
  raw: z.unknown().optional(),
});

export const eventSchema = z.object({
  id: z.string().min(1),
  sessionId: z.string().min(1),
  source: z.enum(["claude-code", "opencode", "codex"]),
  type: z.enum([
    "session_start",
    "session_end",
    "tool_call",
    "turn_complete",
    "file_edit",
    "checkpoint",
  ]),
  timestamp: z.string().min(1),
  detail: eventDetailSchema.default({}),
});

/** Parse an unknown body into a KibitzerEvent, or throw a ZodError. */
export function parseEvent(input: unknown): KibitzerEvent {
  return eventSchema.parse(input) as KibitzerEvent;
}
